name: UCP Prototype
on: 
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
jobs:
  correctness-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Dump GitHub Event Payload for Debugging
        run: |
          echo "--- GITHUB EVENT PATH CONTENT ---"
          cat ${{ github.event_path }}
          echo "--- END GITHUB EVENT PATH CONTENT ---"
          echo ""
          echo "--- GITHUB EVENT JSON (for easy parsing) ---"
          echo "${{ toJson(github.event) }}"
          echo "--- END GITHUB EVENT JSON ---"
      - name: Set up script
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: correctness-tester/go.sum
      - name: Correctness test
        id: grader
        working-directory: correctness-tester
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          go run main.go
      - name: Grade result
        if: ${{ failure() && steps.grader.outcome == 'failure' }}
        run: |
          echo "Homework grading failed. Please check the 'Correctness test' step for details."
          exit 1
